# Dockerfile.build
FROM golang:1.24

RUN apt update && apt install -y gcc libsqlite3-dev

WORKDIR /app
COPY . .

RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o ./build/bot_app ./cmd/bot/main.go
